target-version = "py313"

[lint.isort]
force-sort-within-sections = true
known-first-party = ["custom_components.techem", "homeassistant", "pytest_homeassistant_custom_component"]
combine-as-imports = true
split-on-trailing-comma = false
