name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: requirements_test.txt
      - name: Install dependencies
        run: pip install -r requirements_test.txt
      - name: Run tests
        run: pytest --cov=custom_components.techem --cov-report=term-missing
